import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BudgetProvider } from "@/context/ContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Money Tracker",
  description: "Generated by Money Tracker",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BudgetProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </BudgetProvider>
    </html>
  );
}
